import sys
import subprocess
import os

# [AUTO-GENERATED by AutoFACS Level 10 Agent]
# Derived from: BOOTLOADER.md (Section II: Initialization Sequence)

def check_hardware():
    """Step 1: Hardware Guard (MPS Verification)"""
    try:
        import torch
        # Level 6 Constraint: Must target Apple Silicon
        if torch.backends.mps.is_available():
            return "ONLINE (MPS Active)"
        return "OFFLINE (MPS Unavailable)"
    except ImportError:
        return "CRITICAL: PyTorch not installed"

def check_portal():
    """Step 2: Portal Guard (Cloud Connectivity)"""
    try:
        # Level 5: Direct terminal execution via subprocess
        # checks for 'gdrive' remote as per FSD
        result = subprocess.run(['rclone', 'listremotes'], capture_output=True, text=True)
        if "gdrive:" in result.stdout:
            return "CONNECTED (Iron Gate Open)"
        return "DISCONNECTED (Remote 'gdrive:' missing)"
    except FileNotFoundError:
        return "CRITICAL: Rclone binary missing"

def check_persistence():
    """Step 4: Persistence Guard (Level 4 History Tracking)"""
    # Ensures no 'vibe coding' happens without saving state
    result = subprocess.run(['git', 'status', '--porcelain'], capture_output=True, text=True)
    if not result.stdout.strip():
        return "CLEAN"
    return "DIRTY (Commit Required)"

def main():
    print(f"\n⚡ AutoFACS Level 10 Bootloader ⚡")
    print("-----------------------------------")
    
    # Sequence enforcement
    print(f"[*] Hardware Guard:   {check_hardware()}")
    print(f"[*] Portal Guard:     {check_portal()}")
    
    git_status = check_persistence()
    print(f"[*] Persistence:      {git_status}")
    
    if "DIRTY" in git_status:
        print("\n⚠️  ACTION REQUIRED: Uncommitted changes detected.")
        print("    Run: git commit -m 'Update documentation and push'")
    else:
        print("\n✅ System Ready. Awaiting FSD Directives.")

if __name__ == "__main__":
    main()
