#!/bin/bash
# AutoFACS Level 10: FSD Enforcement Script
# Generated by golden_schema_executor.py

rclone move "gdrive:AutoAI_Projects/FACS_Automation/Technical Documentation/img_expressions/final_model_V5.pth" "gdrive:model_weights/V5" -v
rclone move "gdrive:AutoAI_Projects/FACS_Automation/Technical Documentation/img_expressions/final_model_V4.pth" "gdrive:model_weights/V4" -v
rclone move "gdrive:AutoAI_Projects/FACS_Automation/Technical Documentation/img_expressions/vit_final_independent_V5/model.safetensors" "gdrive:model_weights/V5" -v
rclone move "gdrive:AutoFACS_Project/ml_expressions/img_expressions/sup_training/V41_20260125_175823/emotion_classifier_model/model.safetensors" "gdrive:model_weights/V41" -v
rclone move "gdrive:AutoFACS_Project/ml_expressions/img_expressions/sup_training/V41_20260125_175823/relevance_filter_model/model.safetensors" "gdrive:model_weights/V41" -v
rclone move "gdrive:AutoFACS_Project/ml_expressions/img_expressions/sup_training/V40_20251025_193828/emotion_classifier_model/model.safetensors" "gdrive:model_weights/V40" -v
rclone move "gdrive:AutoFACS_Project/ml_expressions/img_expressions/sup_training/V40_20251025_193828/relevance_filter_model/model.safetensors" "gdrive:model_weights/V40" -v
rclone move "gdrive:AutoFACS_Project/ml_expressions/img_expressions/sup_training/V39_20251022_093948/emotion_classifier_model/model.safetensors" "gdrive:model_weights/V39" -v
rclone move "gdrive:AutoFACS_Project/ml_expressions/img_expressions/sup_training/V39_20251022_093948/relevance_filter_model/model.safetensors" "gdrive:model_weights/V39" -v
rclone move "gdrive:AutoFACS_Project/ml_expressions/img_expressions/sup_training/V38_20251021_123355/emotion_classifier_model/model.safetensors" "gdrive:model_weights/V38" -v
rclone move "gdrive:AutoFACS_Project/ml_expressions/img_expressions/sup_training/V38_20251021_123355/relevance_filter_model/model.safetensors" "gdrive:model_weights/V38" -v
rclone move "gdrive:AutoFACS_Project/ml_expressions/img_expressions/sup_training/V41_20260125_175823/stage_2_emotion_model_training/checkpoint-1848/rng_state.pth" "gdrive:model_weights/V41" -v
rclone move "gdrive:AutoFACS_Project/ml_expressions/img_expressions/sup_training/V41_20260125_175823/stage_2_emotion_model_training/checkpoint-1848/scheduler.pt" "gdrive:model_weights/V41" -v
rclone move "gdrive:AutoFACS_Project/ml_expressions/img_expressions/sup_training/V41_20260125_175823/stage_2_emotion_model_training/checkpoint-1848/optimizer.pt" "gdrive:model_weights/V41" -v
rclone move "gdrive:AutoFACS_Project/ml_expressions/img_expressions/sup_training/V41_20260125_175823/stage_2_emotion_model_training/checkpoint-1848/model.safetensors" "gdrive:model_weights/V41" -v
rclone move "gdrive:AutoFACS_Project/ml_expressions/img_expressions/sup_training/V41_20260125_175823/stage_2_emotion_model_training/checkpoint-1543/rng_state.pth" "gdrive:model_weights/V41" -v
rclone move "gdrive:AutoFACS_Project/ml_expressions/img_expressions/sup_training/V41_20260125_175823/stage_2_emotion_model_training/checkpoint-1543/scheduler.pt" "gdrive:model_weights/V41" -v
rclone move "gdrive:AutoFACS_Project/ml_expressions/img_expressions/sup_training/V41_20260125_175823/stage_2_emotion_model_training/checkpoint-1543/optimizer.pt" "gdrive:model_weights/V41" -v
rclone move "gdrive:AutoFACS_Project/ml_expressions/img_expressions/sup_training/V41_20260125_175823/stage_2_emotion_model_training/checkpoint-1543/model.safetensors" "gdrive:model_weights/V41" -v
rclone move "gdrive:AutoFACS_Project/ml_expressions/img_expressions/sup_training/V41_20260125_175823/stage_2_emotion_model_training/checkpoint-1235/rng_state.pth" "gdrive:model_weights/V41" -v
rclone move "gdrive:AutoFACS_Project/ml_expressions/img_expressions/sup_training/V41_20260125_175823/stage_2_emotion_model_training/checkpoint-1235/scheduler.pt" "gdrive:model_weights/V41" -v
rclone move "gdrive:AutoFACS_Project/ml_expressions/img_expressions/sup_training/V41_20260125_175823/stage_2_emotion_model_training/checkpoint-1235/optimizer.pt" "gdrive:model_weights/V41" -v
rclone move "gdrive:AutoFACS_Project/ml_expressions/img_expressions/sup_training/V41_20260125_175823/stage_2_emotion_model_training/checkpoint-1235/model.safetensors" "gdrive:model_weights/V41" -v
rclone move "gdrive:AutoFACS_Project/ml_expressions/img_expressions/sup_training/V41_20260125_175823/stage_2_emotion_model_training/checkpoint-926/rng_state.pth" "gdrive:model_weights/V41" -v
rclone move "gdrive:AutoFACS_Project/ml_expressions/img_expressions/sup_training/V41_20260125_175823/stage_2_emotion_model_training/checkpoint-926/scheduler.pt" "gdrive:model_weights/V41" -v
rclone move "gdrive:AutoFACS_Project/ml_expressions/img_expressions/sup_training/V41_20260125_175823/stage_2_emotion_model_training/checkpoint-926/optimizer.pt" "gdrive:model_weights/V41" -v
rclone move "gdrive:AutoFACS_Project/ml_expressions/img_expressions/sup_training/V41_20260125_175823/stage_2_emotion_model_training/checkpoint-926/model.safetensors" "gdrive:model_weights/V41" -v
rclone move "gdrive:AutoFACS_Project/ml_expressions/img_expressions/sup_training/V41_20260125_175823/stage_2_emotion_model_training/checkpoint-617/rng_state.pth" "gdrive:model_weights/V41" -v
rclone move "gdrive:AutoFACS_Project/ml_expressions/img_expressions/sup_training/V41_20260125_175823/stage_2_emotion_model_training/checkpoint-617/scheduler.pt" "gdrive:model_weights/V41" -v
rclone move "gdrive:AutoFACS_Project/ml_expressions/img_expressions/sup_training/V41_20260125_175823/stage_2_emotion_model_training/checkpoint-617/optimizer.pt" "gdrive:model_weights/V41" -v
rclone move "gdrive:AutoFACS_Project/ml_expressions/img_expressions/sup_training/V41_20260125_175823/stage_2_emotion_model_training/checkpoint-617/model.safetensors" "gdrive:model_weights/V41" -v
rclone move "gdrive:AutoFACS_Project/ml_expressions/img_expressions/sup_training/V41_20260125_175823/stage_2_emotion_model_training/checkpoint-308/rng_state.pth" "gdrive:model_weights/V41" -v
rclone move "gdrive:AutoFACS_Project/ml_expressions/img_expressions/sup_training/V41_20260125_175823/stage_2_emotion_model_training/checkpoint-308/scheduler.pt" "gdrive:model_weights/V41" -v
rclone move "gdrive:AutoFACS_Project/ml_expressions/img_expressions/sup_training/V41_20260125_175823/stage_2_emotion_model_training/checkpoint-308/optimizer.pt" "gdrive:model_weights/V41" -v
rclone move "gdrive:AutoFACS_Project/ml_expressions/img_expressions/sup_training/V41_20260125_175823/stage_2_emotion_model_training/checkpoint-308/model.safetensors" "gdrive:model_weights/V41" -v
rclone move "gdrive:AutoFACS_Project/ml_expressions/img_expressions/sup_training/V41_20260125_175823/stage_1_relevance_model_training/checkpoint-6720/rng_state.pth" "gdrive:model_weights/V41" -v
rclone move "gdrive:AutoFACS_Project/ml_expressions/img_expressions/sup_training/V41_20260125_175823/stage_1_relevance_model_training/checkpoint-6720/scheduler.pt" "gdrive:model_weights/V41" -v
rclone move "gdrive:AutoFACS_Project/ml_expressions/img_expressions/sup_training/V41_20260125_175823/stage_1_relevance_model_training/checkpoint-6720/optimizer.pt" "gdrive:model_weights/V41" -v
rclone move "gdrive:AutoFACS_Project/ml_expressions/img_expressions/sup_training/V41_20260125_175823/stage_1_relevance_model_training/checkpoint-6720/model.safetensors" "gdrive:model_weights/V41" -v
rclone move "gdrive:AutoFACS_Project/ml_expressions/img_expressions/sup_training/V41_20260125_175823/stage_1_relevance_model_training/checkpoint-5376/rng_state.pth" "gdrive:model_weights/V41" -v
rclone move "gdrive:AutoFACS_Project/ml_expressions/img_expressions/sup_training/V41_20260125_175823/stage_1_relevance_model_training/checkpoint-5376/optimizer.pt" "gdrive:model_weights/V41" -v
rclone move "gdrive:AutoFACS_Project/ml_expressions/img_expressions/sup_training/V41_20260125_175823/stage_1_relevance_model_training/checkpoint-5376/scheduler.pt" "gdrive:model_weights/V41" -v
rclone move "gdrive:AutoFACS_Project/ml_expressions/img_expressions/sup_training/V41_20260125_175823/stage_1_relevance_model_training/checkpoint-5376/model.safetensors" "gdrive:model_weights/V41" -v
rclone move "gdrive:AutoFACS_Project/ml_expressions/img_expressions/sup_training/V41_20260125_175823/stage_1_relevance_model_training/checkpoint-4032/rng_state.pth" "gdrive:model_weights/V41" -v
rclone move "gdrive:AutoFACS_Project/ml_expressions/img_expressions/sup_training/V41_20260125_175823/stage_1_relevance_model_training/checkpoint-4032/scheduler.pt" "gdrive:model_weights/V41" -v
rclone move "gdrive:AutoFACS_Project/ml_expressions/img_expressions/sup_training/V41_20260125_175823/stage_1_relevance_model_training/checkpoint-4032/optimizer.pt" "gdrive:model_weights/V41" -v
rclone move "gdrive:AutoFACS_Project/ml_expressions/img_expressions/sup_training/V41_20260125_175823/stage_1_relevance_model_training/checkpoint-4032/model.safetensors" "gdrive:model_weights/V41" -v
rclone move "gdrive:AutoFACS_Project/ml_expressions/img_expressions/sup_training/V41_20260125_175823/stage_1_relevance_model_training/checkpoint-2688/rng_state.pth" "gdrive:model_weights/V41" -v
rclone move "gdrive:AutoFACS_Project/ml_expressions/img_expressions/sup_training/V41_20260125_175823/stage_1_relevance_model_training/checkpoint-2688/scheduler.pt" "gdrive:model_weights/V41" -v
rclone move "gdrive:AutoFACS_Project/ml_expressions/img_expressions/sup_training/V41_20260125_175823/stage_1_relevance_model_training/checkpoint-2688/optimizer.pt" "gdrive:model_weights/V41" -v
rclone move "gdrive:AutoFACS_Project/ml_expressions/img_expressions/sup_training/V41_20260125_175823/stage_1_relevance_model_training/checkpoint-2688/model.safetensors" "gdrive:model_weights/V41" -v
rclone move "gdrive:AutoFACS_Project/ml_expressions/img_expressions/sup_training/V41_20260125_175823/stage_1_relevance_model_training/checkpoint-1344/rng_state.pth" "gdrive:model_weights/V41" -v
rclone move "gdrive:AutoFACS_Project/ml_expressions/img_expressions/sup_training/V41_20260125_175823/stage_1_relevance_model_training/checkpoint-1344/scheduler.pt" "gdrive:model_weights/V41" -v
rclone move "gdrive:AutoFACS_Project/ml_expressions/img_expressions/sup_training/V41_20260125_175823/stage_1_relevance_model_training/checkpoint-1344/optimizer.pt" "gdrive:model_weights/V41" -v
rclone move "gdrive:AutoFACS_Project/ml_expressions/img_expressions/sup_training/V41_20260125_175823/stage_1_relevance_model_training/checkpoint-1344/model.safetensors" "gdrive:model_weights/V41" -v
rclone move "gdrive:AutoFACS_Project/ml_expressions/img_expressions/sup_training/V40_20251025_193828/stage_2_emotion_model_training/checkpoint-1848/optimizer.pt" "gdrive:model_weights/V40" -v
rclone move "gdrive:AutoFACS_Project/ml_expressions/img_expressions/sup_training/V40_20251025_193828/stage_2_emotion_model_training/checkpoint-1848/scheduler.pt" "gdrive:model_weights/V40" -v
rclone move "gdrive:AutoFACS_Project/ml_expressions/img_expressions/sup_training/V40_20251025_193828/stage_2_emotion_model_training/checkpoint-1848/rng_state.pth" "gdrive:model_weights/V40" -v
rclone move "gdrive:AutoFACS_Project/ml_expressions/img_expressions/sup_training/V40_20251025_193828/stage_2_emotion_model_training/checkpoint-1848/model.safetensors" "gdrive:model_weights/V40" -v
rclone move "gdrive:AutoFACS_Project/ml_expressions/img_expressions/sup_training/V40_20251025_193828/stage_2_emotion_model_training/checkpoint-1543/rng_state.pth" "gdrive:model_weights/V40" -v
rclone move "gdrive:AutoFACS_Project/ml_expressions/img_expressions/sup_training/V40_20251025_193828/stage_2_emotion_model_training/checkpoint-1543/optimizer.pt" "gdrive:model_weights/V40" -v
rclone move "gdrive:AutoFACS_Project/ml_expressions/img_expressions/sup_training/V40_20251025_193828/stage_2_emotion_model_training/checkpoint-1543/scheduler.pt" "gdrive:model_weights/V40" -v
rclone move "gdrive:AutoFACS_Project/ml_expressions/img_expressions/sup_training/V40_20251025_193828/stage_2_emotion_model_training/checkpoint-1543/model.safetensors" "gdrive:model_weights/V40" -v
rclone move "gdrive:AutoFACS_Project/ml_expressions/img_expressions/sup_training/V40_20251025_193828/stage_2_emotion_model_training/checkpoint-1235/rng_state.pth" "gdrive:model_weights/V40" -v
rclone move "gdrive:AutoFACS_Project/ml_expressions/img_expressions/sup_training/V40_20251025_193828/stage_2_emotion_model_training/checkpoint-1235/optimizer.pt" "gdrive:model_weights/V40" -v
rclone move "gdrive:AutoFACS_Project/ml_expressions/img_expressions/sup_training/V40_20251025_193828/stage_2_emotion_model_training/checkpoint-1235/scheduler.pt" "gdrive:model_weights/V40" -v
rclone move "gdrive:AutoFACS_Project/ml_expressions/img_expressions/sup_training/V40_20251025_193828/stage_2_emotion_model_training/checkpoint-1235/model.safetensors" "gdrive:model_weights/V40" -v
rclone move "gdrive:AutoFACS_Project/ml_expressions/img_expressions/sup_training/V40_20251025_193828/stage_2_emotion_model_training/checkpoint-926/scheduler.pt" "gdrive:model_weights/V40" -v
rclone move "gdrive:AutoFACS_Project/ml_expressions/img_expressions/sup_training/V40_20251025_193828/stage_2_emotion_model_training/checkpoint-926/rng_state.pth" "gdrive:model_weights/V40" -v
rclone move "gdrive:AutoFACS_Project/ml_expressions/img_expressions/sup_training/V40_20251025_193828/stage_2_emotion_model_training/checkpoint-926/optimizer.pt" "gdrive:model_weights/V40" -v
rclone move "gdrive:AutoFACS_Project/ml_expressions/img_expressions/sup_training/V40_20251025_193828/stage_2_emotion_model_training/checkpoint-926/model.safetensors" "gdrive:model_weights/V40" -v
rclone move "gdrive:AutoFACS_Project/ml_expressions/img_expressions/sup_training/V40_20251025_193828/stage_2_emotion_model_training/checkpoint-617/rng_state.pth" "gdrive:model_weights/V40" -v
rclone move "gdrive:AutoFACS_Project/ml_expressions/img_expressions/sup_training/V40_20251025_193828/stage_2_emotion_model_training/checkpoint-617/scheduler.pt" "gdrive:model_weights/V40" -v
rclone move "gdrive:AutoFACS_Project/ml_expressions/img_expressions/sup_training/V40_20251025_193828/stage_2_emotion_model_training/checkpoint-617/optimizer.pt" "gdrive:model_weights/V40" -v
rclone move "gdrive:AutoFACS_Project/ml_expressions/img_expressions/sup_training/V40_20251025_193828/stage_2_emotion_model_training/checkpoint-617/model.safetensors" "gdrive:model_weights/V40" -v
rclone move "gdrive:AutoFACS_Project/ml_expressions/img_expressions/sup_training/V40_20251025_193828/stage_2_emotion_model_training/checkpoint-308/rng_state.pth" "gdrive:model_weights/V40" -v
rclone move "gdrive:AutoFACS_Project/ml_expressions/img_expressions/sup_training/V40_20251025_193828/stage_2_emotion_model_training/checkpoint-308/scheduler.pt" "gdrive:model_weights/V40" -v
rclone move "gdrive:AutoFACS_Project/ml_expressions/img_expressions/sup_training/V40_20251025_193828/stage_2_emotion_model_training/checkpoint-308/optimizer.pt" "gdrive:model_weights/V40" -v
rclone move "gdrive:AutoFACS_Project/ml_expressions/img_expressions/sup_training/V40_20251025_193828/stage_2_emotion_model_training/checkpoint-308/model.safetensors" "gdrive:model_weights/V40" -v
rclone move "gdrive:AutoFACS_Project/ml_expressions/img_expressions/sup_training/V40_20251025_193828/stage_1_relevance_model_training/checkpoint-6720/rng_state.pth" "gdrive:model_weights/V40" -v
rclone move "gdrive:AutoFACS_Project/ml_expressions/img_expressions/sup_training/V40_20251025_193828/stage_1_relevance_model_training/checkpoint-6720/scheduler.pt" "gdrive:model_weights/V40" -v
rclone move "gdrive:AutoFACS_Project/ml_expressions/img_expressions/sup_training/V40_20251025_193828/stage_1_relevance_model_training/checkpoint-6720/optimizer.pt" "gdrive:model_weights/V40" -v
rclone move "gdrive:AutoFACS_Project/ml_expressions/img_expressions/sup_training/V40_20251025_193828/stage_1_relevance_model_training/checkpoint-6720/model.safetensors" "gdrive:model_weights/V40" -v
rclone move "gdrive:AutoFACS_Project/ml_expressions/img_expressions/sup_training/V40_20251025_193828/stage_1_relevance_model_training/checkpoint-5376/rng_state.pth" "gdrive:model_weights/V40" -v
rclone move "gdrive:AutoFACS_Project/ml_expressions/img_expressions/sup_training/V40_20251025_193828/stage_1_relevance_model_training/checkpoint-5376/optimizer.pt" "gdrive:model_weights/V40" -v
rclone move "gdrive:AutoFACS_Project/ml_expressions/img_expressions/sup_training/V40_20251025_193828/stage_1_relevance_model_training/checkpoint-5376/scheduler.pt" "gdrive:model_weights/V40" -v
rclone move "gdrive:AutoFACS_Project/ml_expressions/img_expressions/sup_training/V40_20251025_193828/stage_1_relevance_model_training/checkpoint-5376/model.safetensors" "gdrive:model_weights/V40" -v
rclone move "gdrive:AutoFACS_Project/ml_expressions/img_expressions/sup_training/V40_20251025_193828/stage_1_relevance_model_training/checkpoint-4032/rng_state.pth" "gdrive:model_weights/V40" -v
rclone move "gdrive:AutoFACS_Project/ml_expressions/img_expressions/sup_training/V40_20251025_193828/stage_1_relevance_model_training/checkpoint-4032/optimizer.pt" "gdrive:model_weights/V40" -v
rclone move "gdrive:AutoFACS_Project/ml_expressions/img_expressions/sup_training/V40_20251025_193828/stage_1_relevance_model_training/checkpoint-4032/scheduler.pt" "gdrive:model_weights/V40" -v
rclone move "gdrive:AutoFACS_Project/ml_expressions/img_expressions/sup_training/V40_20251025_193828/stage_1_relevance_model_training/checkpoint-4032/model.safetensors" "gdrive:model_weights/V40" -v
rclone move "gdrive:AutoFACS_Project/ml_expressions/img_expressions/sup_training/V40_20251025_193828/stage_1_relevance_model_training/checkpoint-2688/rng_state.pth" "gdrive:model_weights/V40" -v
rclone move "gdrive:AutoFACS_Project/ml_expressions/img_expressions/sup_training/V40_20251025_193828/stage_1_relevance_model_training/checkpoint-2688/scheduler.pt" "gdrive:model_weights/V40" -v
rclone move "gdrive:AutoFACS_Project/ml_expressions/img_expressions/sup_training/V40_20251025_193828/stage_1_relevance_model_training/checkpoint-2688/optimizer.pt" "gdrive:model_weights/V40" -v
rclone move "gdrive:AutoFACS_Project/ml_expressions/img_expressions/sup_training/V40_20251025_193828/stage_1_relevance_model_training/checkpoint-2688/model.safetensors" "gdrive:model_weights/V40" -v
rclone move "gdrive:AutoFACS_Project/ml_expressions/img_expressions/sup_training/V40_20251025_193828/stage_1_relevance_model_training/checkpoint-1344/rng_state.pth" "gdrive:model_weights/V40" -v
rclone move "gdrive:AutoFACS_Project/ml_expressions/img_expressions/sup_training/V40_20251025_193828/stage_1_relevance_model_training/checkpoint-1344/scheduler.pt" "gdrive:model_weights/V40" -v
rclone move "gdrive:AutoFACS_Project/ml_expressions/img_expressions/sup_training/V40_20251025_193828/stage_1_relevance_model_training/checkpoint-1344/optimizer.pt" "gdrive:model_weights/V40" -v
rclone move "gdrive:AutoFACS_Project/ml_expressions/img_expressions/sup_training/V40_20251025_193828/stage_1_relevance_model_training/checkpoint-1344/model.safetensors" "gdrive:model_weights/V40" -v
rclone move "gdrive:AutoFACS_Project/ml_expressions/img_expressions/sup_training/V38_20251021_123355/stage_1_relevance_model_training/checkpoint-1344/rng_state.pth" "gdrive:model_weights/V38" -v
rclone move "gdrive:AutoFACS_Project/ml_expressions/img_expressions/sup_training/V38_20251021_123355/stage_1_relevance_model_training/checkpoint-1344/optimizer.pt" "gdrive:model_weights/V38" -v
rclone move "gdrive:AutoFACS_Project/ml_expressions/img_expressions/sup_training/V38_20251021_123355/stage_1_relevance_model_training/checkpoint-1344/scheduler.pt" "gdrive:model_weights/V38" -v
rclone move "gdrive:AutoFACS_Project/ml_expressions/img_expressions/sup_training/V38_20251021_123355/stage_1_relevance_model_training/checkpoint-1344/model.safetensors" "gdrive:model_weights/V38" -v
rclone move "gdrive:AutoFACS_Project/ml_expressions/img_expressions/sup_training/V39_20251022_093948/stage_2_emotion_model_training/checkpoint-926/rng_state.pth" "gdrive:model_weights/V39" -v
rclone move "gdrive:AutoFACS_Project/ml_expressions/img_expressions/sup_training/V39_20251022_093948/stage_2_emotion_model_training/checkpoint-926/scheduler.pt" "gdrive:model_weights/V39" -v
rclone move "gdrive:AutoFACS_Project/ml_expressions/img_expressions/sup_training/V39_20251022_093948/stage_2_emotion_model_training/checkpoint-926/optimizer.pt" "gdrive:model_weights/V39" -v
rclone move "gdrive:AutoFACS_Project/ml_expressions/img_expressions/sup_training/V39_20251022_093948/stage_2_emotion_model_training/checkpoint-926/model.safetensors" "gdrive:model_weights/V39" -v
rclone move "gdrive:AutoFACS_Project/ml_expressions/img_expressions/sup_training/V39_20251022_093948/stage_2_emotion_model_training/checkpoint-617/scheduler.pt" "gdrive:model_weights/V39" -v
rclone move "gdrive:AutoFACS_Project/ml_expressions/img_expressions/sup_training/V39_20251022_093948/stage_2_emotion_model_training/checkpoint-617/rng_state.pth" "gdrive:model_weights/V39" -v
rclone move "gdrive:AutoFACS_Project/ml_expressions/img_expressions/sup_training/V39_20251022_093948/stage_2_emotion_model_training/checkpoint-617/optimizer.pt" "gdrive:model_weights/V39" -v
rclone move "gdrive:AutoFACS_Project/ml_expressions/img_expressions/sup_training/V39_20251022_093948/stage_2_emotion_model_training/checkpoint-617/model.safetensors" "gdrive:model_weights/V39" -v
rclone move "gdrive:AutoFACS_Project/ml_expressions/img_expressions/sup_training/V39_20251022_093948/stage_2_emotion_model_training/checkpoint-308/rng_state.pth" "gdrive:model_weights/V39" -v
rclone move "gdrive:AutoFACS_Project/ml_expressions/img_expressions/sup_training/V39_20251022_093948/stage_2_emotion_model_training/checkpoint-308/scheduler.pt" "gdrive:model_weights/V39" -v
rclone move "gdrive:AutoFACS_Project/ml_expressions/img_expressions/sup_training/V39_20251022_093948/stage_2_emotion_model_training/checkpoint-308/optimizer.pt" "gdrive:model_weights/V39" -v
rclone move "gdrive:AutoFACS_Project/ml_expressions/img_expressions/sup_training/V39_20251022_093948/stage_2_emotion_model_training/checkpoint-308/model.safetensors" "gdrive:model_weights/V39" -v
rclone move "gdrive:AutoFACS_Project/ml_expressions/img_expressions/sup_training/V39_20251022_093948/stage_1_relevance_model_training/checkpoint-6720/rng_state.pth" "gdrive:model_weights/V39" -v
rclone move "gdrive:AutoFACS_Project/ml_expressions/img_expressions/sup_training/V39_20251022_093948/stage_1_relevance_model_training/checkpoint-6720/scheduler.pt" "gdrive:model_weights/V39" -v
rclone move "gdrive:AutoFACS_Project/ml_expressions/img_expressions/sup_training/V39_20251022_093948/stage_1_relevance_model_training/checkpoint-6720/optimizer.pt" "gdrive:model_weights/V39" -v
rclone move "gdrive:AutoFACS_Project/ml_expressions/img_expressions/sup_training/V39_20251022_093948/stage_1_relevance_model_training/checkpoint-6720/model.safetensors" "gdrive:model_weights/V39" -v
rclone move "gdrive:AutoFACS_Project/ml_expressions/img_expressions/sup_training/V39_20251022_093948/stage_1_relevance_model_training/checkpoint-5376/scheduler.pt" "gdrive:model_weights/V39" -v
rclone move "gdrive:AutoFACS_Project/ml_expressions/img_expressions/sup_training/V39_20251022_093948/stage_1_relevance_model_training/checkpoint-5376/rng_state.pth" "gdrive:model_weights/V39" -v
rclone move "gdrive:AutoFACS_Project/ml_expressions/img_expressions/sup_training/V39_20251022_093948/stage_1_relevance_model_training/checkpoint-5376/optimizer.pt" "gdrive:model_weights/V39" -v
rclone move "gdrive:AutoFACS_Project/ml_expressions/img_expressions/sup_training/V39_20251022_093948/stage_1_relevance_model_training/checkpoint-5376/model.safetensors" "gdrive:model_weights/V39" -v
rclone move "gdrive:AutoFACS_Project/ml_expressions/img_expressions/sup_training/V39_20251022_093948/stage_1_relevance_model_training/checkpoint-4032/rng_state.pth" "gdrive:model_weights/V39" -v
rclone move "gdrive:AutoFACS_Project/ml_expressions/img_expressions/sup_training/V39_20251022_093948/stage_1_relevance_model_training/checkpoint-4032/scheduler.pt" "gdrive:model_weights/V39" -v
rclone move "gdrive:AutoFACS_Project/ml_expressions/img_expressions/sup_training/V39_20251022_093948/stage_1_relevance_model_training/checkpoint-4032/optimizer.pt" "gdrive:model_weights/V39" -v
rclone move "gdrive:AutoFACS_Project/ml_expressions/img_expressions/sup_training/V39_20251022_093948/stage_1_relevance_model_training/checkpoint-4032/model.safetensors" "gdrive:model_weights/V39" -v
rclone move "gdrive:AutoFACS_Project/ml_expressions/img_expressions/sup_training/V39_20251022_093948/stage_1_relevance_model_training/checkpoint-2688/rng_state.pth" "gdrive:model_weights/V39" -v
rclone move "gdrive:AutoFACS_Project/ml_expressions/img_expressions/sup_training/V39_20251022_093948/stage_1_relevance_model_training/checkpoint-2688/scheduler.pt" "gdrive:model_weights/V39" -v
rclone move "gdrive:AutoFACS_Project/ml_expressions/img_expressions/sup_training/V39_20251022_093948/stage_1_relevance_model_training/checkpoint-2688/optimizer.pt" "gdrive:model_weights/V39" -v
rclone move "gdrive:AutoFACS_Project/ml_expressions/img_expressions/sup_training/V39_20251022_093948/stage_1_relevance_model_training/checkpoint-2688/model.safetensors" "gdrive:model_weights/V39" -v
rclone move "gdrive:AutoFACS_Project/ml_expressions/img_expressions/sup_training/V39_20251022_093948/stage_1_relevance_model_training/checkpoint-1344/rng_state.pth" "gdrive:model_weights/V39" -v
rclone move "gdrive:AutoFACS_Project/ml_expressions/img_expressions/sup_training/V39_20251022_093948/stage_1_relevance_model_training/checkpoint-1344/scheduler.pt" "gdrive:model_weights/V39" -v
rclone move "gdrive:AutoFACS_Project/ml_expressions/img_expressions/sup_training/V39_20251022_093948/stage_1_relevance_model_training/checkpoint-1344/optimizer.pt" "gdrive:model_weights/V39" -v
rclone move "gdrive:AutoFACS_Project/ml_expressions/img_expressions/sup_training/V39_20251022_093948/stage_1_relevance_model_training/checkpoint-1344/model.safetensors" "gdrive:model_weights/V39" -v
rclone move "gdrive:AutoFACS_Project/ml_expressions/img_expressions/sup_training/V38_20251021_123355/stage_2_emotion_model_training/checkpoint-2574/optimizer.pt" "gdrive:model_weights/V38" -v
rclone move "gdrive:AutoFACS_Project/ml_expressions/img_expressions/sup_training/V38_20251021_123355/stage_2_emotion_model_training/checkpoint-2574/rng_state.pth" "gdrive:model_weights/V38" -v
rclone move "gdrive:AutoFACS_Project/ml_expressions/img_expressions/sup_training/V38_20251021_123355/stage_2_emotion_model_training/checkpoint-2574/scheduler.pt" "gdrive:model_weights/V38" -v
rclone move "gdrive:AutoFACS_Project/ml_expressions/img_expressions/sup_training/V38_20251021_123355/stage_2_emotion_model_training/checkpoint-2574/model.safetensors" "gdrive:model_weights/V38" -v
rclone move "gdrive:AutoFACS_Project/ml_expressions/img_expressions/sup_training/V38_20251021_123355/stage_2_emotion_model_training/checkpoint-2145/scheduler.pt" "gdrive:model_weights/V38" -v
rclone move "gdrive:AutoFACS_Project/ml_expressions/img_expressions/sup_training/V38_20251021_123355/stage_2_emotion_model_training/checkpoint-2145/rng_state.pth" "gdrive:model_weights/V38" -v
rclone move "gdrive:AutoFACS_Project/ml_expressions/img_expressions/sup_training/V38_20251021_123355/stage_2_emotion_model_training/checkpoint-2145/optimizer.pt" "gdrive:model_weights/V38" -v
rclone move "gdrive:AutoFACS_Project/ml_expressions/img_expressions/sup_training/V38_20251021_123355/stage_2_emotion_model_training/checkpoint-2145/model.safetensors" "gdrive:model_weights/V38" -v
rclone move "gdrive:AutoFACS_Project/ml_expressions/img_expressions/sup_training/V38_20251021_123355/stage_2_emotion_model_training/checkpoint-1716/rng_state.pth" "gdrive:model_weights/V38" -v
rclone move "gdrive:AutoFACS_Project/ml_expressions/img_expressions/sup_training/V38_20251021_123355/stage_2_emotion_model_training/checkpoint-1716/optimizer.pt" "gdrive:model_weights/V38" -v
rclone move "gdrive:AutoFACS_Project/ml_expressions/img_expressions/sup_training/V38_20251021_123355/stage_2_emotion_model_training/checkpoint-1716/scheduler.pt" "gdrive:model_weights/V38" -v
rclone move "gdrive:AutoFACS_Project/ml_expressions/img_expressions/sup_training/V38_20251021_123355/stage_2_emotion_model_training/checkpoint-1716/model.safetensors" "gdrive:model_weights/V38" -v
rclone move "gdrive:AutoFACS_Project/ml_expressions/img_expressions/sup_training/V38_20251021_123355/stage_2_emotion_model_training/checkpoint-1287/rng_state.pth" "gdrive:model_weights/V38" -v
rclone move "gdrive:AutoFACS_Project/ml_expressions/img_expressions/sup_training/V38_20251021_123355/stage_2_emotion_model_training/checkpoint-1287/scheduler.pt" "gdrive:model_weights/V38" -v
rclone move "gdrive:AutoFACS_Project/ml_expressions/img_expressions/sup_training/V38_20251021_123355/stage_2_emotion_model_training/checkpoint-1287/optimizer.pt" "gdrive:model_weights/V38" -v
rclone move "gdrive:AutoFACS_Project/ml_expressions/img_expressions/sup_training/V38_20251021_123355/stage_2_emotion_model_training/checkpoint-1287/model.safetensors" "gdrive:model_weights/V38" -v
rclone move "gdrive:AutoFACS_Project/ml_expressions/img_expressions/sup_training/V38_20251021_123355/stage_2_emotion_model_training/checkpoint-858/optimizer.pt" "gdrive:model_weights/V38" -v
rclone move "gdrive:AutoFACS_Project/ml_expressions/img_expressions/sup_training/V38_20251021_123355/stage_2_emotion_model_training/checkpoint-858/scheduler.pt" "gdrive:model_weights/V38" -v
rclone move "gdrive:AutoFACS_Project/ml_expressions/img_expressions/sup_training/V38_20251021_123355/stage_2_emotion_model_training/checkpoint-858/rng_state.pth" "gdrive:model_weights/V38" -v
rclone move "gdrive:AutoFACS_Project/ml_expressions/img_expressions/sup_training/V38_20251021_123355/stage_2_emotion_model_training/checkpoint-858/model.safetensors" "gdrive:model_weights/V38" -v
rclone move "gdrive:AutoFACS_Project/ml_expressions/img_expressions/sup_training/V38_20251021_123355/stage_2_emotion_model_training/checkpoint-429/optimizer.pt" "gdrive:model_weights/V38" -v
rclone move "gdrive:AutoFACS_Project/ml_expressions/img_expressions/sup_training/V38_20251021_123355/stage_2_emotion_model_training/checkpoint-429/scheduler.pt" "gdrive:model_weights/V38" -v
rclone move "gdrive:AutoFACS_Project/ml_expressions/img_expressions/sup_training/V38_20251021_123355/stage_2_emotion_model_training/checkpoint-429/rng_state.pth" "gdrive:model_weights/V38" -v
rclone move "gdrive:AutoFACS_Project/ml_expressions/img_expressions/sup_training/V38_20251021_123355/stage_2_emotion_model_training/checkpoint-429/model.safetensors" "gdrive:model_weights/V38" -v
rclone move "gdrive:AutoFACS_Project/ml_expressions/img_expressions/sup_training/V38_20251021_123355/stage_1_relevance_model_training/checkpoint-6720/optimizer.pt" "gdrive:model_weights/V38" -v
rclone move "gdrive:AutoFACS_Project/ml_expressions/img_expressions/sup_training/V38_20251021_123355/stage_1_relevance_model_training/checkpoint-6720/scheduler.pt" "gdrive:model_weights/V38" -v
rclone move "gdrive:AutoFACS_Project/ml_expressions/img_expressions/sup_training/V38_20251021_123355/stage_1_relevance_model_training/checkpoint-6720/rng_state.pth" "gdrive:model_weights/V38" -v
rclone move "gdrive:AutoFACS_Project/ml_expressions/img_expressions/sup_training/V38_20251021_123355/stage_1_relevance_model_training/checkpoint-6720/model.safetensors" "gdrive:model_weights/V38" -v
rclone move "gdrive:AutoFACS_Project/ml_expressions/img_expressions/sup_training/V38_20251021_123355/stage_1_relevance_model_training/checkpoint-5376/rng_state.pth" "gdrive:model_weights/V38" -v
rclone move "gdrive:AutoFACS_Project/ml_expressions/img_expressions/sup_training/V38_20251021_123355/stage_1_relevance_model_training/checkpoint-5376/optimizer.pt" "gdrive:model_weights/V38" -v
rclone move "gdrive:AutoFACS_Project/ml_expressions/img_expressions/sup_training/V38_20251021_123355/stage_1_relevance_model_training/checkpoint-5376/model.safetensors" "gdrive:model_weights/V38" -v
rclone move "gdrive:AutoFACS_Project/ml_expressions/img_expressions/sup_training/V38_20251021_123355/stage_1_relevance_model_training/checkpoint-5376/scheduler.pt" "gdrive:model_weights/V38" -v
rclone move "gdrive:AutoFACS_Project/ml_expressions/img_expressions/sup_training/V38_20251021_123355/stage_1_relevance_model_training/checkpoint-4032/rng_state.pth" "gdrive:model_weights/V38" -v
rclone move "gdrive:AutoFACS_Project/ml_expressions/img_expressions/sup_training/V38_20251021_123355/stage_1_relevance_model_training/checkpoint-4032/optimizer.pt" "gdrive:model_weights/V38" -v
rclone move "gdrive:AutoFACS_Project/ml_expressions/img_expressions/sup_training/V38_20251021_123355/stage_1_relevance_model_training/checkpoint-4032/scheduler.pt" "gdrive:model_weights/V38" -v
rclone move "gdrive:AutoFACS_Project/ml_expressions/img_expressions/sup_training/V38_20251021_123355/stage_1_relevance_model_training/checkpoint-4032/model.safetensors" "gdrive:model_weights/V38" -v
rclone move "gdrive:AutoFACS_Project/ml_expressions/img_expressions/sup_training/V38_20251021_123355/stage_1_relevance_model_training/checkpoint-2688/rng_state.pth" "gdrive:model_weights/V38" -v
rclone move "gdrive:AutoFACS_Project/ml_expressions/img_expressions/sup_training/V38_20251021_123355/stage_1_relevance_model_training/checkpoint-2688/optimizer.pt" "gdrive:model_weights/V38" -v
rclone move "gdrive:AutoFACS_Project/ml_expressions/img_expressions/sup_training/V38_20251021_123355/stage_1_relevance_model_training/checkpoint-2688/model.safetensors" "gdrive:model_weights/V38" -v
rclone move "gdrive:AutoFACS_Project/ml_expressions/img_expressions/sup_training/V38_20251021_123355/stage_1_relevance_model_training/checkpoint-2688/scheduler.pt" "gdrive:model_weights/V38" -v
rclone move "gdrive:AutoFACS_Project/ml_expressions/img_datasets/synthetic_speech_imgs/Wav2Lip/checkpoints/Wav2Lip-SD-GAN.pt" "gdrive:model_weights/V2" -v
rclone move "gdrive:AutoFACS_Project/ml_expressions/img_expressions/pre-trained models/finetuned_vit_model/checkpoint-11124/optimizer.pt" "gdrive:model_weights/Unsorted" -v
rclone move "gdrive:AutoFACS_Project/ml_expressions/img_expressions/pre-trained models/finetuned_vit_model/checkpoint-14832/optimizer.pt" "gdrive:model_weights/Unsorted" -v
rclone move "gdrive:AutoFACS_Project/ml_expressions/img_expressions/pre-trained models/finetuned_vit_model/checkpoint-7416/optimizer.pt" "gdrive:model_weights/Unsorted" -v
rclone move "gdrive:AutoFACS_Project/ml_expressions/img_expressions/pre-trained models/finetuned_vit_model/checkpoint-18540/optimizer.pt" "gdrive:model_weights/Unsorted" -v
rclone move "gdrive:AutoFACS_Project/ml_expressions/img_expressions/pre-trained models/finetuned_vit_model/checkpoint-3708/optimizer.pt" "gdrive:model_weights/Unsorted" -v
rclone move "gdrive:AutoFACS_Project/ml_expressions/img_expressions/pre-trained models/finetuned_vit_model/checkpoint-11124/model.safetensors" "gdrive:model_weights/Unsorted" -v
rclone move "gdrive:AutoFACS_Project/ml_expressions/img_expressions/pre-trained models/finetuned_vit_model/checkpoint-3708/model.safetensors" "gdrive:model_weights/Unsorted" -v
rclone move "gdrive:AutoFACS_Project/ml_expressions/img_expressions/pre-trained models/finetuned_vit_model/checkpoint-18540/model.safetensors" "gdrive:model_weights/Unsorted" -v
rclone move "gdrive:AutoFACS_Project/ml_expressions/img_expressions/pre-trained models/finetuned_vit_model/checkpoint-14832/model.safetensors" "gdrive:model_weights/Unsorted" -v
rclone move "gdrive:AutoFACS_Project/ml_expressions/img_expressions/pre-trained models/finetuned_vit_model/checkpoint-7416/model.safetensors" "gdrive:model_weights/Unsorted" -v
rclone move "gdrive:AutoFACS_Project/ml_expressions/img_expressions/pre-trained models/finetuned_vit_model/checkpoint-7416/rng_state.pth" "gdrive:model_weights/Unsorted" -v
rclone move "gdrive:AutoFACS_Project/ml_expressions/img_expressions/pre-trained models/finetuned_vit_model/checkpoint-3708/scheduler.pt" "gdrive:model_weights/Unsorted" -v
rclone move "gdrive:AutoFACS_Project/ml_expressions/img_expressions/pre-trained models/finetuned_vit_model/checkpoint-7416/scheduler.pt" "gdrive:model_weights/Unsorted" -v
rclone move "gdrive:AutoFACS_Project/ml_expressions/img_expressions/pre-trained models/finetuned_vit_model/checkpoint-14832/scheduler.pt" "gdrive:model_weights/Unsorted" -v
rclone move "gdrive:AutoFACS_Project/ml_expressions/img_expressions/pre-trained models/finetuned_vit_model/checkpoint-11124/rng_state.pth" "gdrive:model_weights/Unsorted" -v
rclone move "gdrive:AutoFACS_Project/ml_expressions/img_expressions/pre-trained models/finetuned_vit_model/checkpoint-3708/rng_state.pth" "gdrive:model_weights/Unsorted" -v
rclone move "gdrive:AutoFACS_Project/ml_expressions/img_expressions/pre-trained models/finetuned_vit_model/checkpoint-11124/scheduler.pt" "gdrive:model_weights/Unsorted" -v
rclone move "gdrive:AutoFACS_Project/ml_expressions/img_expressions/pre-trained models/finetuned_vit_model/checkpoint-14832/rng_state.pth" "gdrive:model_weights/Unsorted" -v
rclone move "gdrive:AutoFACS_Project/ml_expressions/img_expressions/pre-trained models/finetuned_vit_model/checkpoint-18540/rng_state.pth" "gdrive:model_weights/Unsorted" -v
rclone move "gdrive:AutoFACS_Project/ml_expressions/img_expressions/pre-trained models/finetuned_vit_model/checkpoint-18540/scheduler.pt" "gdrive:model_weights/Unsorted" -v
